#ifndef REMOTEUSERONLINESTATUS_H
#define REMOTEUSERONLINESTATUS_H

enum RemoteUserOnlineStatus {
    USERUNKNOWNONLINESTATUS,
    USEROFFLINE,
    USERONLINE,
    USERWANTTOCHAT,
    USERAWAY,
    USERDONT_DISTURB
};

#endif // REMOTEUSERONLINESTATUS_H
