.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2013 KillYourTV <killyourtv@i2pmail.org>
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH i2p-messenger 1 "April 28, 2013"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
i2p-messenger \- chat client for the I2P network
.SH SYNOPSIS
.B i2p-messenger
.SH DESCRIPTION
This manual page documents briefly the
.B i2p-messenger
command.
.PP

 I2P-Messenger is an I2P-internal, serverless, anonymous and secure (end-to-end
 encrypted) instant messaging client with support for file transfers that
 connects via the SAM bridge.

 Contacts that are not yet on your contact list can be found by using Seedless.
